@url = http://localhost:4000
# @url = https://pure-atoll-47649.herokuapp.com
###
POST {{url}}/dialog_flow
Content-Type: application/json

{
    "text":"sdfsdfsdf"
}

### 
POST {{url}}/isUserValid 
Content-Type: application/json

{
    "empId": 64
}
